# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Prepare
        run: |
          git config --global user.email "example-user@example.com"
          git config --global user.name "Example User"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Pack to tgz
        run: npm pack --pack-destination=${{ runner.temp }}
      - name: Install globally from tgz
        run: npm install -g ${{ runner.temp }}/rafw87-create-vite-dashboard-*.tgz
      - name: Run create script from installed version
        run: npx tsx scripts/test-execute.ts ${{ runner.temp }}/generated-dashboard
      - name: Lint generated dashboard
        run: npm run lint
        working-directory: ${{ runner.temp }}/generated-dashboard
      - name: Build generated dashboard
        run: npm run build
        working-directory: ${{ runner.temp }}/generated-dashboard
      - name: Run prettier on generated dashboard
        run: npm run prettier:fix
        working-directory: ${{ runner.temp }}/generated-dashboard
      - name: Check if working tree is clean
        run: git diff --exit-code
        working-directory: ${{ runner.temp }}/generated-dashboard
